### ISSUE TITLE
src/casm/crystallography/Lattice.cc  ... compilation aborted

### ISSUE THREAD

**Issue by foxik0070** [prisms-center/CASMcode#94]
Hello,

I have problem with compilation *casm-v0.2.1* from source. I see this error

```console
icpc -DHAVE_CONFIG_H -I. -I./include/casm/external/qhull/libqhull_r/ -I./include/casm/external/gzstream -I/apps/all/Boost/1.63.0-intel-2017a-Python-2.7.13/include -I/apps/all/imkl/2017.1.132-iimpi-2017a/mkl/include -I/apps/all/Boost/1.63.0-intel-2017a-Python-2.7.13/include -I/apps/all/Python/2.7.13/include -DTXT_VERSION=\"v0.2.1\" -DEIGEN_DEFAULT_DENSE_INDEX_TYPE=long -DGZSTREAM_NAMESPACE=gz -I./include -I./include/casm/external/gzstream -I./include/casm/external/qhull/libqhullcpp -O2 -xHost -ftz -fp-speculation=safe -fp-model source -MT src/casm/crystallography/Lattice.lo -MD -MP -MF src/casm/crystallography/.deps/Lattice.Tpo -c src/casm/crystallography/Lattice.cc  -fPIC -DPIC -o src/casm/crystallography/.libs/Lattice.o
src/casm/crystallography/Lattice.cc(636): error: no instance of overloaded function "std::ptr_fun" matches the argument list
            argument types are: (<unknown-type>)
      return (inv_lat_column_mat() * recip).cwiseAbs().unaryExpr(std::ptr_fun(ceil)).colwise().maxCoeff().cast<int>();
                                                                 ^
/apps/all/GCCcore/6.3.0/include/c++/6.3.0/bits/stl_function.h(864): note: this candidate was rejected because at least one template argument could not be deduced
      ptr_fun(_Result (*__x)(_Arg1, _Arg2))
      ^
/apps/all/GCCcore/6.3.0/include/c++/6.3.0/bits/stl_function.h(838): note: this candidate was rejected because at least one template argument could not be deduced
      ptr_fun(_Result (*__x)(_Arg))
      ^

src/casm/crystallography/Lattice.cc(636): error: type name is not allowed
      return (inv_lat_column_mat() * recip).cwiseAbs().unaryExpr(std::ptr_fun(ceil)).colwise().maxCoeff().cast<int>();
                                                                                                               ^

src/casm/crystallography/Lattice.cc(636): error: expected an expression
      return (inv_lat_column_mat() * recip).cwiseAbs().unaryExpr(std::ptr_fun(ceil)).colwise().maxCoeff().cast<int>();
```

**I have dependencies**
* Boost 1.63.0
* Python 2.7.13 (scipy, numpy, ...)
* Scons 3.0.0
* Intel 2017 with icc 2017.1.132-GCC-6.3.0-2.27

Some ideas?

**Comment by bpuchala** [comment]
'ptr_fun' was deprecated and this problem can occur with more recent compilers.  I believe this has been fixed in the development branch, 0.2.X.

**Comment by foxik0070** [comment]
@bpuchala I tried compile branch 0.2.X, but i have problem.

```bash
CASMcode [0.2.X]$ scons configure
scons: Reading SConscript files ...
  File "/apps/easybuild/sources/c/CASMcode/CASMcode/SConstruct", line 552

    print "rm", path

             ^

SyntaxError: invalid syntax
```

**I have dependencies**

Boost 1.63.0
Python 2.7.13 (scipy, numpy, ...)
Scons 3.0.0
Intel 2017 with icc 2017.1.132-GCC-6.3.0-2.27

Some ideas?

**Comment by bpuchala** [comment]
Ah, this is a scons 3.0.0 problem.  Using a previous version of scons should solve it.  Python2/3 compatibility is under development.

You could also build with autotools (./bootstrap.sh; ./configure (+options); make; make install).

**Comment by foxik0070** [comment]
@bpuchala

I change SCons version from 3.0.0 to 2.5.1 and tried build again. I see next problem. I applied https://github.com/prisms-center/CASMcode/issues/40, but problem not resolved.

Dependencies:
 * SCons/2.5.1-intel-2017a-Python-2.7.13
 * Python/2.7.13
 * icc/2017.1.132-GCC-6.3.0-2.27 (intel/2017a)
 * M4/1.4.18-GCCcore-6.3.0
 * Autoconf/2.69-intel-2017a
 * Boost/1.63.0-intel-2017a-Python-2.7.13

```bash
icpc -DTXT_VERSION=\"v0.2.1-57-g59d14f-dirty\" -DEIGEN_DEFAULT_DENSE_INDEX_TYPE=long -DGZSTREAM_NAMESPACE=gz -I./include -I./include/casm/external/gzstream -I./include/casm/external/qhull/libqhullcpp -g -O2 -o .libs/casm ./apps/casm/casm.o  -L/apps/all/Boost/1.63.0-intel-2017a-Python-2.7.13/lib ./.libs/libcasm.so /apps/all/GCCcore/6.3.0/lib/../lib64/libstdc++.so -lm -lboost_system -lboost_filesystem -lboost_program_options -lboost_regex -lboost_chrono -ldl -lz -Wl,-rpath,/apps/all/CASMcode/0.2.X-intel-2017a-Python-2.7.13/lib -Wl,-rpath,/apps/all/GCCcore/6.3.0/lib/../lib64
./.libs/libcasm.so: undefined reference to `qh_meminit'
./.libs/libcasm.so: undefined reference to `qh_setin'
./.libs/libcasm.so: undefined reference to `qh_initstatistics'
./.libs/libcasm.so: undefined reference to `qh_produce_output2'
./.libs/libcasm.so: undefined reference to `qh_check_points'
./.libs/libcasm.so: undefined reference to `qh_setendpointer'
./.libs/libcasm.so: undefined reference to `qh_clear_outputflags'
./.libs/libcasm.so: undefined reference to `qh_init_B'
./.libs/libcasm.so: undefined reference to `qh_initqhull_outputflags'
./.libs/libcasm.so: undefined reference to `qh_errexit'
./.libs/libcasm.so: undefined reference to `qh_malloc'
./.libs/libcasm.so: undefined reference to `qh_nextridge3d'
./.libs/libcasm.so: undefined reference to `qh_errexit_rbox'
./.libs/libcasm.so: undefined reference to `qh_sethalfspace_all'
./.libs/libcasm.so: undefined reference to `qh_freeqhull'
./.libs/libcasm.so: undefined reference to `qh_lib_check'
./.libs/libcasm.so: undefined reference to `qh_setfeasible'
./.libs/libcasm.so: undefined reference to `qh_getangle'
./.libs/libcasm.so: undefined reference to `qh_facetarea'
./.libs/libcasm.so: undefined reference to `qh_check_output'
./.libs/libcasm.so: undefined reference to `qh_initflags'
./.libs/libcasm.so: undefined reference to `qh_fprintf_stderr'
./.libs/libcasm.so: undefined reference to `qh_settempfree'
./.libs/libcasm.so: undefined reference to `qh_pointid'
./.libs/libcasm.so: undefined reference to `qh_exit'
./.libs/libcasm.so: undefined reference to `qh_memfreeshort'
./.libs/libcasm.so: undefined reference to `qh_fprintf(qhT*, _IO_FILE*, int, char const*, ...)'
./.libs/libcasm.so: undefined reference to `qh_rboxpoints'
./.libs/libcasm.so: undefined reference to `qh_fprintf_rbox(qhT*, _IO_FILE*, int, char const*, ...)'
./.libs/libcasm.so: undefined reference to `qh_vertexneighbors'
./.libs/libcasm.so: undefined reference to `qh_initqhull_start2'
./.libs/libcasm.so: undefined reference to `qh_getarea'
./.libs/libcasm.so: undefined reference to `qh_checkflags'
./.libs/libcasm.so: undefined reference to `qh_memcheck'
./.libs/libcasm.so: undefined reference to `qh_getcentrum'
./.libs/libcasm.so: undefined reference to `qh_facetvertices'
./.libs/libcasm.so: undefined reference to `qh_qhull'
./.libs/libcasm.so: undefined reference to `qh_facetcenter'
./.libs/libcasm.so: undefined reference to `qh_outerinner'
./.libs/libcasm.so: undefined reference to `qh_prepare_output
```

**Comment by bpuchala** [comment]
I'm not sure why, but this means qhull (src/casm/externel/qhull) is not being compiled or linked with ICC. I don't think we've seen this with GCC / Clang. Unless there is some way to use our institutional license with Travis I'm not sure we can really commit to ICC support right now. But please continue to post ICC issues / solutions / pull requests for fixes.
